<?php
/**
 * Created by PhpStorm.
 * User: dell
 * Date: 9/26/15
 * Time: 5:48 PM
 */

$title = 'Delete education';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($education->level); ?>' by
    '<?php echo $this->escapeHtml($education->description); ?>'
</p>

<?php
$url = $this->url('education', array(
    'action' => 'delete',
    'id' => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $education->id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>
