<?php
/**
 * Created by PhpStorm.
 * User: dell
 * Date: 9/26/15
 * Time: 5:47 PM
 */


$name = 'Education List';
$this->headTitle($name);
?>
<h1><?php echo $this->escapeHtml($name); ?></h1>
<p>
    <a href="<?php echo $this->url('education', array('action'=>'add')); ?>">Add new education</a>
</p>

<table class="table">
    <tr>
        <th>Level</th>
        <th>Description</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($educations as $education) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($education->level); ?></td>
            <td><?php echo $this->escapeHtml($education->description);?></td>
            <td>
                <a href="<?php echo $this->url('education', array('action'=>'edit', 'id' => $education->id)); ?>">Edit</a>
                <a href="<?php echo $this->url('education', array('action'=>'delete', 'id' => $education->id)); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>