<?php
/**
 * Created by PhpStorm.
 * User: dell
 * Date: 9/26/15
 * Time: 5:47 PM
 */


$name = 'People List';
$this->headTitle($name);
?>
<h1><?php echo $this->escapeHtml($name); ?></h1>
<p>
    <a href="<?php echo $this->url('person', array('action'=>'add')); ?>">Add new person</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Interest</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($persons as $person) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($person->name); ?></td>
            <td><?php echo $this->escapeHtml($person->interest);?></td>
            <td>
                <a href="<?php echo $this->url('person', array('action'=>'edit', 'id' => $person->id)); ?>">Edit</a>
                <a href="<?php echo $this->url('person', array('action'=>'delete', 'id' => $person->id)); ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>